version: '3.9'
services:
  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - ${PWD}/.typebot-build/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
  typebot-builder:
    build:
      context: .
      args:
        - SCOPE=builder
    depends_on:
      - typebot-db
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env
    GOOGLE_CLIENT_ID=198365357808-s0762gh2iuk7ul05sdhths6bradg6h2d.apps.googleusercontent.com
    GOOGLE_CLIENT_SECRET=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
  typebot-viewer:
    build:
      context: .
      args:
        - SCOPE=viewer
    ports:
      - '8081:3000'
    env_file: .env
